services:
  sober:
    container_name: sober
    image: sober
    restart: unless-stopped
    ports:
      - "89:80"
    environment:
      - TZ=America/Chicago
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
      - homepage.group=Personal
      - homepage.name=Sᴏʙᴇᴙ Tᴙᴀᴄᴋᴇᴙ
      - homepage.icon=https://sober.postfmly.com/sober.png
      - homepage.href=https://sober.postfmly.com/
      - homepage.description=sober.postfmly.com
networks: {}

x-dockge:
  urls:
    - https://sober.postfmly.com
