services:
  sober:
    container_name: sober
    image: git.postfmly.com/admin/sober
    restart: unless-stopped
    ports:
      - "89:80"
    environment:
      - TZ=America/Chicago
    labels:
      - wud.display.name=Sᴏʙᴇᴙ Tᴙᴀᴄᴋᴇᴙ
      - homepage.group=Personal
      - homepage.name=Sᴏʙᴇᴙ Tᴙᴀᴄᴋᴇᴙ
      - homepage.icon=https://sober.postfmly.com/sober.png
      - homepage.href=https://sober.postfmly.com/
      - homepage.description=sober.postfmly.com
    platform: linux/arm64

networks: {}

x-dockge:
  urls:
    - https://sober.postfmly.com
