services:
  sober-tracker:
    image: sober-tracker
    container_name: sober-tracker
    restart: unless-stopped
    ports:
      - 89:80
    environment:
      - TZ=America/Chicago
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
